import json
from pathlib import Path
p=Path('Scripts/P4/localization.json');d=json.loads(p.read_text(encoding='utf-8-sig'))
extra={
'Video.Header':['{0} | VIDEO TARGET: UAV-{1} | ACTIVE UAV: {2}','{0} | 视频目标：UAV-{1} | 当前无人机：{2}'],
'Video.Feed':['{0}\nModel: N/A | Link: {1}\n{2}\n{3}','{0}\n机型：暂无 | 连接：{1}\n{2}\n{3}'],
'Video.Heading':['PRIMARY VIDEO / {0}','主视频 / {0}'],
'Video.Details':['{0} | Camera: N/A | Resolution: {1} | FPS: {2} | {3}','{0} | 相机：暂无 | 分辨率：{1} | 帧率：{2} | {3}'],
'Command.Header':['COMMAND CENTER | {0} | {1} | Clients {2}/3','指挥中心 | {0} | {1} | 客户端 {2}/3'],
'Command.Count':['{0} UAV | {1} ONLINE | {2} ALERTS','无人机 {0} | 在线 {1} | 告警 {2}'],
'Command.Metrics':['ALT {0} | SPD {1} | BAT {2}','高度 {0} | 速度 {1} | 电量 {2}'],
'Command.Link':['LINK {0}\nMISSION {1}','连接 {0}\n任务 {1}'],
'Log.Count':['EVENT / OPERATION LOG (UTC) | Critical {0} | Warning {1}','事件 / 操作日志（UTC）| 严重 {0} | 警告 {1}'],
}
sources={
'MAP OPERATIONS':('Map.Header','MAP OPERATIONS','地图作业'),
'Map initializing':('Map.Init','Map initializing','地图初始化中'),
'Select a UAV here or on the map.':('Map.Select','Select a UAV here or on the map.','在列表或地图中选择无人机。'),
'Locate':('Map.Locate','LOCATE','定位'),
'无人机视频监看系统  /  UAV VIDEO MONITOR CENTER':('Video.Title','UAV VIDEO MONITOR CENTER','无人机视频监看系统'),
'AIRCRAFT\n飞机列表':('Video.Aircraft','AIRCRAFT','无人机列表'),
'SELECT PRIMARY FEED':('Video.SelectFeed','SELECT VIDEO TARGET','选择视频目标'),
'MODEL N/A = no aircraft model field\nVisual presets are not aircraft specifications.':('Video.ModelNotice','Model not supplied by Registry. Visual presets are not aircraft specifications.','注册表未提供机型，外观预设不代表飞机规格。'),
'PRIMARY VIDEO':('Video.Primary','PRIMARY VIDEO','主视频'),
'NO UAV SELECTED\nNO ACTIVE STREAM':('Video.NoTarget','NO TARGET\nNO ACTIVE STREAM','未指定目标\n无活动视频流'),
'NO UAV REGISTERED\nNO ACTIVE STREAM':('Video.NoTarget','NO TARGET\nNO ACTIVE STREAM','未指定目标\n无活动视频流'),
'Camera: N/A':('Video.Camera','Camera: N/A','相机：暂无'),
'AI DETECTION\n智能检测':('Video.AI','AI DETECTION','智能检测'),
'AI DETECTION NOT CONNECTED':('Video.AINotConnected','AI DETECTION NOT CONNECTED','智能检测未连接'),
'人员  /  PERSON\n\n车辆  /  VEHICLE\n\n无人机  /  UAV\n\n异常行为  /  BEHAVIOR\n\n其他目标  /  OTHER':('Video.Categories','PERSON\n\nVEHICLE\n\nUAV\n\nBEHAVIOR\n\nOTHER','人员\n\n车辆\n\n无人机\n\n异常行为\n\n其他目标'),
'RECENT ALERTS\n最近告警':('Video.RecentAlerts','RECENT ALERTS','最近告警'),
'NO ACTIVE ALERTS':('Video.NoAlerts','NO ACTIVE ALERTS','无活动告警'),
'Reserved fields\nTitle · UAV · Target\nTimestamp · Severity':('Video.ReservedFields','Reserved fields\nTitle · UAV · Target\nTimestamp · Severity','预留字段\n标题 · 无人机 · 目标\n时间 · 严重程度'),
'UAV ONLINE: N/A\nAI ENGINE: NOT CONNECTED\nSTORAGE: N/A\nNETWORK: N/A':('Video.ReservedStatus','UAV ONLINE: N/A\nAI ENGINE: NOT CONNECTED\nSTORAGE: N/A\nNETWORK: N/A','在线无人机：暂无\nAI 引擎：未连接\n存储：暂无\n网络：暂无'),
'Reserved for future integration':('Common.Reserved','Reserved for future integration','预留，等待后续接入'),
'4路 / 4 VIEW':('Video.Four','4 VIEW','4 格布局'),
'6路 / 6 VIEW':('Video.Six','6 VIEW','6 格布局'),
'FOCUS':('Video.Focus','FOCUS','聚焦布局'),
'SET AS ACTIVE UAV':('Video.SetActive','SET AS ACTIVE UAV','设为当前无人机'),
'REFRESH / RETRY':('Video.Retry','RETRY','重试'),
'SINGLE ACTIVE PLAYER  ·  Secondary feeds are reserved slots  ·  No AI backend connected':('Video.Single','SINGLE ACTIVE PLAYER · Secondary feeds are reserved slots · No AI backend connected','单个活动播放器 · 其他视频格位为预留 · 未连接 AI 后端'),
'RESERVED\n\nNO UAV ASSIGNED':('Video.Reserved','RESERVED\nNO UAV ASSIGNED','预留格位\n未分配无人机'),
'NO SOURCE\nAssign a video source to this UAV':('Video.NoSource','NO SOURCE\nAssign a video source to this UAV','无视频源\n请为此无人机配置视频源'),
'COMMAND  /  安防指挥中心':('Command.Title','SECURITY COMMAND CENTER','安防指挥中心'),
'UAV FLEET  /  机队态势':('Command.Fleet','UAV FLEET','机队态势'),
'等待注册表数据':('Command.Waiting','Waiting for Registry','等待注册表数据'),
'告警中心 · 最近200条 / 本会话':('Command.Alerts','ALERTS · Last 200 / Session','告警中心 · 最近200条 / 本会话'),
'TACTICAL DATA  /  无人机态势':('Command.Tactical','TACTICAL DATA','无人机态势'),
'未选择无人机':('Command.NoSelection','No UAV selected','未选择无人机'),
'ALT N/A   SPD N/A   BAT N/A':('Command.NoMetrics','ALT N/A | SPD N/A | BAT N/A','高度 暂无 | 速度 暂无 | 电量 暂无'),
'LINK N/A  |  MISSION N/A':('Command.NoMission','LINK N/A | MISSION N/A','连接 暂无 | 任务 暂无'),
'任务请求结果以返回状态为准。路径规划请使用独立 Map Client。':('Command.ActionNotice','Request results require Backend confirmation. Use Map for route editing.','请求结果以后端确认为准，航线编辑请使用地图客户端。'),
'UAV DETAILS / ACTIONS':('Command.Details','UAV DETAILS / ACTIONS','无人机详情 / 操作'),
'暂停请求':('Command.Pause','REQUEST PAUSE','暂停请求'),
'恢复请求':('Command.Resume','REQUEST RESUME','恢复请求'),
'尚未收到告警（本会话）':('Command.NoAlerts','No alerts in this session','本会话尚未收到告警'),
'选择无人机':('Command.Select','SELECT UAV','选择无人机'),
'标记已处理':('Command.Handled','MARK HANDLED','标记已处理'),
'移除记录':('Command.Remove','REMOVE RECORD','移除记录'),
'CLEAR DISPLAY':('Log.Clear','CLEAR DISPLAY','清空显示'),
'No events in this view':('Log.Empty','No events in this view','当前视图暂无事件'),
'连接':('Common.Online','ONLINE','在线'),
'失联':('Common.Lost','LOST','失联'),
'离线':('Common.Offline','OFFLINE','离线'),
'已选择':('Common.Selected','SELECTED','已选择'),
'选择':('Common.Select','SELECT','选择'),
'展开':('Common.Expand','EXPAND','展开'),
'收起':('Common.Collapse','COLLAPSE','收起'),
'重命名':('Common.Rename','RENAME','重命名'),
}
for source,(key,en,zh) in sources.items():extra[key]=[en,zh]
for word,zh in {'RESERVED':'预留','INFO':'信息','WARNING':'警告','CRITICAL':'严重','RECORD':'录像','PLAYBACK':'回放','SCREENSHOT':'截图','ALERT FILTER':'告警筛选','NO TARGET':'未指定目标','NO SOURCE':'无视频源','CONNECTING':'连接中','PAGE READY / WAITING VIDEO':'页面就绪 / 等待视频','PLAYING':'正在播放','STALLED / NO FRAMES':'视频停滞 / 无新帧','OFFLINE / LOAD FAILED':'离线 / 加载失败','MEDIA ERROR':'媒体错误','RETRYING':'重试中','CLOSED':'已关闭','SOURCE SET':'已配置视频源','VIDEO SLOT\nNO ACTIVE STREAM':'视频格位\n无活动视频流','MONITOR':'监控','PLAN_EDIT':'方案编辑','ALERT_RESPONSE':'告警响应','MISSION_EXECUTION':'任务执行','ALL':'全部','SYSTEM':'系统','OPERATION':'操作','ALERT':'告警','MISSION':'任务','PLAN':'方案'}.items():extra['Status.'+word.replace(' ','_').replace('/','_').replace('\n','_')]=[word,zh]
for event,en,zh in [
('PLAN_CREATED','Plan {plan_name} created','已创建方案 {plan_name}'),('PLAN_UPDATED','Plan {plan_name} updated','已更新方案 {plan_name}'),('PLAN_COPIED','Plan {plan_name} copied as draft','已将方案 {plan_name} 复制为草稿'),
('MISSION_CREATED','Mission {mission_name} created','已创建任务 {mission_name}'),('MISSION_UPDATED','Mission {mission_name} renamed','已重命名任务 {mission_name}'),('MISSION_DELETED','Mission {target_id} deleted','已删除任务 {target_id}'),
('UAV_ASSIGNED','{uav_id} assigned to mission {mission_name}','{uav_id} 已分配至任务 {mission_name}'),('UAV_UNASSIGNED','Mission {mission_name} UAV unassigned','任务 {mission_name} 已取消无人机分配'),
('ROUTE_CREATED','Mission {mission_name} route saved','任务 {mission_name} 航线已保存'),('ROUTE_UPDATED','Mission {mission_name} route updated','任务 {mission_name} 航线已更新'),('ROUTE_CLEARED','Mission {mission_name} route cleared','任务 {mission_name} 航线已清空'),
('PLAN_VALIDATED','Plan {plan_name} configuration checked','方案 {plan_name} 配置已检查'),('PLAN_REVIEWED','Plan {plan_name} reviewed','方案 {plan_name} 已审阅'),('PLAN_DEPLOYED','Plan {plan_name} deployed. Execution has not started.','方案 {plan_name} 已部署，执行尚未启动')]:extra['Events.'+event]=[en,zh]
d.update(extra);p.write_text(json.dumps(d,ensure_ascii=False,indent=2),encoding='utf-8');Path('Scripts/P4/source_aliases.json').write_text(json.dumps({source:v[0] for source,v in sources.items()},ensure_ascii=False,indent=2),encoding='utf-8')
