import assert from 'node:assert/strict';
import fs from 'node:fs';
const base=process.env.P1_HTTP??'http://127.0.0.1:19780',ws=process.env.P1_WS??'ws://127.0.0.1:19781/ws';
const out=process.env.P53_EVIDENCE_DIR??'Evidence/TASK-P5.3/protocol/p53';fs.mkdirSync(out,{recursive:true});
const clients=[],passed=[],traffic=[];const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function api(path,body,code){const r=await fetch(base+path,body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{});const data=await r.json();traffic.push({path,status:r.status,data});if(code)assert.equal(data.code,code);else assert(r.ok,JSON.stringify(data));return data;}
async function connect(role){const id=crypto.randomUUID();await api('/api/context/clients',{instance_id:id,client_id:'P53-QA-'+role,client_role:role,hostname:'SYNTHETIC-QA',app_version:'P5.3'});const c={id,role,socket:new WebSocket(ws),events:[]};clients.push(c);c.socket.onmessage=e=>c.events.push(JSON.parse(e.data));await new Promise((r,j)=>{c.socket.onopen=r;c.socket.onerror=j;});c.socket.send(JSON.stringify({type:'subscribe_context',instance_id:id}));for(let i=0;i<100&&!c.events.some(e=>e.type==='context_subscribed');i++)await sleep(50);assert(c.events.some(e=>e.type==='context_subscribed'));c.timer=setInterval(()=>c.socket.send(JSON.stringify({type:'context_ping',hydrated:true})),2000);return c;}
const pass=name=>{passed.push(name);console.log('PASS '+name);};
try{
 const command=await connect('Command'),map=await connect('Map');let plan='',mission='',session='';const state=()=>api('/api/security-plans');
 const send=async(c,action,extra={},code)=>api('/api/security-plans',{instance_id:c.id,action,plan_id:plan,mission_id:mission,expected_version:(await state()).version,...extra},code);
 let r=await send(command,'create_plan',{name:'P5.3 geometry protocol',default_mission_name:'Task 01'});plan=r.plan_id;mission=r.mission_id;await send(command,'assign',{assigned_uav_id:'UAV-03'});
 session=(await send(map,'begin_route_edit',{content_revision:(await state()).plans[plan].content_revision})).edit_session_id;
 const path={pathId:3,bClosedLoop:false,waypoints:[0,1,2,3].map(i=>({sequence:i+1,latitude:39.98+(i>=2?.0001:0),longitude:116.34+(i===1||i===2?.0001:0),altitude:80,segmentSpeed:50,waitTime:0,location:{x:i>=2?1000:0,y:i===1||i===2?1000:0,z:8000}}))};
 await send(map,'save_route',{edit_session_id:session,path,keep_editing:true});pass('Open route persists with four logical waypoints');
 path.bClosedLoop=true;const canonical=structuredClone(path);delete canonical.bClosedLoop;canonical.closedRoute=true;r=await send(map,'save_route',{edit_session_id:session,path:canonical,keep_editing:true});const rid=r.state.missions[mission].route_id;assert.equal(r.state.paths[rid].waypoints.length,4);assert.equal(r.state.paths[rid].bClosedLoop,true);pass('Closed route persists without duplicated first point');
 path.waypoints.push({...structuredClone(path.waypoints[3]),sequence:5});await send(map,'save_route',{edit_session_id:session,path,keep_editing:true});path.waypoints.splice(2,1);path.waypoints.forEach((p,i)=>p.sequence=i+1);r=await send(map,'save_route',{edit_session_id:session,path,keep_editing:true});assert.equal(r.state.paths[rid].bClosedLoop,true);pass('Add and delete preserve closed topology');
 await send(map,'finish_route_edit',{edit_session_id:session});await send(command,'validate');await send(command,'review');r=await send(command,'deploy');const old=r.state.deployments,oldId=r.state.plans[plan].deployment_id;
 await send(command,'request_map_plan_move');await sleep(100);assert(map.events.some(e=>e.type==='MapRouteEditRequested'&&e.payload.mode==='MOVE'&&e.payload.plan_id===plan));pass('Command routes Move Plan to independent Map through Backend');
 session=(await send(map,'begin_plan_move')).edit_session_id;assert(session);const before=(await state()).paths[rid];await send(map,'cancel_plan_move',{edit_session_id:session});assert.deepEqual((await state()).paths[rid],before);pass('Cancel keeps authoritative coordinates unchanged');
 session=(await send(map,'begin_plan_move')).edit_session_id;const translated=structuredClone(before);for(const p of translated.waypoints){p.location.x+=3000;p.location.y-=2000;p.latitude+=.0003;}
 await send(command,'execution_start',{request_id:crypto.randomUUID()},'PLAN_EDIT_IN_PROGRESS');pass('Active move lease blocks mission start');
 r=await send(map,'move_plan',{edit_session_id:session,paths:{[rid]:translated}});assert.equal(r.state.plans[plan].status,'DEPLOYED');const did=r.state.plans[plan].deployment_id;assert.notEqual(did,oldId);assert.deepEqual(r.state.deployments[oldId],old[oldId]);assert.deepEqual(r.state.deployments[did].snapshot.paths[rid],r.state.paths[rid]);assert.equal(r.state.paths[rid].bClosedLoop,true);pass('Confirmed translation preserves deployed state and aligns route with replacement snapshot');
 await sleep(100);assert(map.events.some(e=>e.type==='SecurityPlansChanged'&&e.payload.plans[plan]?.deployment_id===did));pass('New geometry is broadcast over WebSocket');
 r=await send(command,'execution_start',{request_id:crypto.randomUUID()});const eid=r.execution_id;assert.deepEqual(r.state.executions[eid].route_snapshot,r.state.paths[rid]);await send(map,'begin_plan_move',{},'PLAN_EXECUTING');await send(command,'request_map_plan_move',{},'PLAN_EXECUTING');pass('Execution uses moved geometry and blocks both move entry paths');
 for(let i=0;i<100;i++){r=await state();if(r.executions[eid].state==='EXECUTING')break;await sleep(100);}await send(command,'execution_pause',{execution_id:eid,request_id:crypto.randomUUID(),control_version:r.executions[eid].control_version});await send(map,'begin_plan_move',{},'PLAN_EXECUTING');pass('Paused execution also blocks moving');
 fs.writeFileSync(out+'/result.json',JSON.stringify({synthetic:true,passed,traffic},null,2));
}finally{for(const c of clients){clearInterval(c.timer);c.socket.close();}}
